# Generated by Django 5.1.2 on 2024-10-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
